### ISSUE TITLE
publicPath failing in Webpack 2

### ISSUE THREAD

**Issue by scott-thrillist** [jeerbl/webfonts-loader#1]
Getting this when I try to build:

`Module build failed: TypeError: Cannot read property 'publicPath' of undefined
    at Object.module.exports (/app/node_modules/webfonts-loader/index.js:146:16)`

So I patched the code directly with better object checking:

`(opts.output && opts.output.publicPath) ? opts.output.publicPath : '/'`

Then it magically seemed to work. Question is, is this just a bandaid for a problem in my setup?

**Comment by jeerbl** [comment]
Fixed in v0.0.5 (6272827);

**Comment by scott-thrillist** [comment]
Hey man, sorry I just got back from vacation. Thanks for looking into this. I completely deleted /node_modules, updated package.json to `"webfonts-loader": "0.2.4"`, ran an npm install and have woff2 working, which is great.

Issue remains where the CSS font path is still root vs /build/. If you'd like my webpack.config let me know where I can email it to.
