### ISSUE TITLE
Output CSS not respecting the output path

### ISSUE THREAD

**Issue by scott-thrillist** [jeerbl/webfonts-loader#2]
It seems the issue in #1 is affecting the output publicPath in the CSS:

`@font-face{
  font-family:"icons";
  src:url(/e6b2c7284ec73c1b3092436005eddf81-icons.woff) format("woff")
}`

It should point to /build/[...].woff like everything else in Webpack. Should we get to the root of the problem in issue #1? Thanks for all your help

**Comment by jeerbl** [comment]
Could you attach your Webpack config?

**Comment by jeerbl** [comment]
By the way, I released 0.2.3 which fixed an issue with the path. You should definitely try it ;)

Keep me updated,
Jerome

**Comment by jeerbl** [comment]
Closing unless someone still got problems.

**Comment by scott-thrillist** [comment]
Hey man, sorry I just got back from vacation. Thanks for looking into this. I completely deleted /node_modules, updated package.json to "webfonts-loader": "0.2.4", ran an npm install and have woff2 working, which is great.

Issue remains where the CSS font path is still root vs /build/. If you'd like my webpack.config let me know where I can email it to.

**Comment by scott-thrillist** [comment]
Ok figured it out. Webpack 2 is strict about passing options to modules, they have to be defined in LoaderOptionsPlugin:

`new webpack.LoaderOptionsPlugin({
    test: /\.js$/,
    options: {
        output: {
            publicPath: '/build/'
        }
    }
})`

There may be a way to get output path without explicitly passing it in Webpack 2 (since output.publicPath is already declared elsewhere) but I'm not sure how.

**Comment by evandiamond** [comment]
I believe this issue still exists in Webpack 4. I'm trying to export to a different folder, but the .css files keeps going into the main icon-folder root.

```
'css': true,
'cssDest': '../../src/views/font-preview.css'
```
